services:
  - type: web
    name: shipper-chat-backend
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: PORT
        value: 8001
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shipper-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: shipper-redis
          property: connectionString
      - key: CORS_ORIGIN
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: NODE_OPTIONS
        value: "--dns-result-order=ipv4first"

  - type: redis
    name: shipper-redis
    plan: free
    region: ohio
    ipAllowList: []

databases:
  - name: shipper-db
    plan: free
    region: ohio
    databaseName: shipper_chat
    user: mrgustaveh
